$clean_ext = 'run.xml tex.bak bbl bcf fdb_latexmk run tdo blg bcf aux snm out toc nav vrb fls log tex.backup';
$pdf_mode = 1;
$pdflatex = 'xelatex -interaction=nonstopmode %O %S -file-line-error -synctex=1';

